### ISSUE TITLE
QR Code to connect to Wi-Fi

### ISSUE THREAD

**Issue by Fleker** [ITVlab/Enterprise-Wi-Fi#1]
If you are connected to Wi-Fi, display a QR code that enables others to connect to that Wi-Fi network.

**Comment by AmGarera** [comment]
So this is to share the enterprise wifi?

**Comment by Fleker** [comment]
Once you've connected, show an optional qr code so other devices can
connect.

**Comment by AmGarera** [comment]
Perhaps [this library](https://github.com/zxing/zxing) will help achieve this without starting from scratch.

**Comment by Fleker** [comment]
Yes it's easy to get a library to do that.
